/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Juegos.BatallaNaval.BatallaNaval;
import Juegos.BuscaMinas.Buscaminas;
import javax.swing.JOptionPane;

/**
 *
 * @author lio
 */
public class JugarRegistrado extends javax.swing.JFrame {
    String usuario;
    /**
     * Creates new form JugarRegistrado
     */
    public JugarRegistrado( String usuario ){
        this.usuario = usuario;
        initComponents();
        textJugador.setText(usuario + "!");
    }
    public JugarRegistrado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textJugador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonBuscaminasFacil = new javax.swing.JButton();
        botonBuscaminasDificil = new javax.swing.JButton();
        botonBuscaMinasExperto = new javax.swing.JButton();
        botonPersonalizado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A Jugar! Disfruta del juego Premium");

        textJugador.setText("Jugador Registrado");

        jLabel2.setText("Hola ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/BarcoJuegos.gif"))); // NOI18N
        jLabel1.setText("Batalla Naval");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/el-buscaminas.png"))); // NOI18N

        botonBuscaminasFacil.setText("Fácil");
        botonBuscaminasFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscaminasFacilActionPerformed(evt);
            }
        });

        botonBuscaminasDificil.setText("Difícil");
        botonBuscaminasDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscaminasDificilActionPerformed(evt);
            }
        });

        botonBuscaMinasExperto.setText("Experto");
        botonBuscaMinasExperto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscaMinasExpertoActionPerformed(evt);
            }
        });

        botonPersonalizado.setText("Personalizado");
        botonPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonalizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 579, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textJugador))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonPersonalizado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonBuscaminasFacil)
                                    .addComponent(botonBuscaminasDificil)
                                    .addComponent(botonBuscaMinasExperto))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textJugador)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBuscaminasFacil)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscaminasDificil)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscaMinasExperto)))
                .addGap(12, 12, 12)
                .addComponent(botonPersonalizado))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        BatallaNaval batallaNaval = new BatallaNaval();
        batallaNaval.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonBuscaminasFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscaminasFacilActionPerformed
        // TODO add your handling code here:
        Buscaminas buscaminas = new Buscaminas(5,3);
        buscaminas.setVisible(true);
    }//GEN-LAST:event_botonBuscaminasFacilActionPerformed

    private void botonBuscaminasDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscaminasDificilActionPerformed
        // TODO add your handling code here:
        Buscaminas buscaminas = new Buscaminas(10, 10);
        buscaminas.setVisible(true);
    }//GEN-LAST:event_botonBuscaminasDificilActionPerformed

    private void botonBuscaMinasExpertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscaMinasExpertoActionPerformed
        // TODO add your handling code here:
        Buscaminas buscaminas = new Buscaminas(20, 40);
        buscaminas.setVisible(true);
    }//GEN-LAST:event_botonBuscaMinasExpertoActionPerformed

    private void botonPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonalizadoActionPerformed
        // TODO add your handling code here:
        /*Convierte una cadena en números*/
        int numeroBotones = Integer.parseInt(JOptionPane.showInputDialog("Longitud lateral: "));
        int numeroMinas = Integer.parseInt(JOptionPane.showInputDialog("Número de Minas: "));
        if(numeroMinas>numeroBotones*numeroBotones){
            JOptionPane.showMessageDialog(this, "El número de minas debe ser menor al número de casillas");
        }else{
            Buscaminas buscaminas = new Buscaminas(numeroBotones, numeroMinas);
            buscaminas.setVisible(true);
        }
    }//GEN-LAST:event_botonPersonalizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugarRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugarRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugarRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugarRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugarRegistrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscaMinasExperto;
    private javax.swing.JButton botonBuscaminasDificil;
    private javax.swing.JButton botonBuscaminasFacil;
    private javax.swing.JButton botonPersonalizado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel textJugador;
    // End of variables declaration//GEN-END:variables
}
